;/*******************************************************************\
;**
;**  This file is part of SNUTOs project, and is made available under
;**  the terms of the GNU General Public License version 3.
;**
;**  Copyright (C) 2025 - Brian DELALEX-FONDU
;**
;\*******************************************************************/

%ifndef EXCEPTION_HANDLERS_INC
%define EXCEPTION_HANDLERS_INC

extern exception0_handler
extern exception1_handler
extern exception2_handler
extern exception3_handler
extern exception4_handler
extern exception5_handler
extern exception6_handler
extern exception7_handler
extern exception8_handler
extern exception9_handler
extern exception10_handler
extern exception11_handler
extern exception12_handler
extern exception13_handler
extern exception14_handler
extern exception15_handler
extern exception16_handler
extern exception17_handler
extern exception18_handler
extern exception19_handler
extern exception20_handler
extern exception21_handler
extern exception22_handler
extern exception23_handler
extern exception24_handler
extern exception25_handler
extern exception26_handler
extern exception27_handler
extern exception28_handler
extern exception29_handler
extern exception30_handler
extern exception31_handler

%endif ;!EXCEPTION_HANDLERS_INC